language: node_js
node_js:
- '14.17.3'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: angular-lab-steamlike
  api_key:
    secure: dfulGA3iPtQU+KT9LT1X4kS00nIAVQ62oq9ghQskfXgwxTxDYb6vM9Ugq3EtZbWoUEZ3AF5d8G6/Ffcfui+tKkS7oHQFB8lfD5uumcvD3YS8xpIcDchU+63KaVTNjJt7H+nRKklA3SKF6UGcOELBB9KF+YNIfqg7zM8/7tVSi5BSVI8KxWmnYQltpPh6G5Md3NM4S71wJ9NDOITtwNYXdisKilUXW1m0a2JaLUFoxONBjfziPemR1N6k1MmlW8X+4Xn7+ioct0VBkDa1l+OZB9tK9tditdI+5pml1gCWcC1WS+76WPrSNw85S4FyVcWmaiT90/DhC0lh40U6qMWYqpxdna1QLCjR+SJjsEPa4422GySuENgUQmCpODaZWrEiMhmrBdDwvT4hPy5f0VYizIYWK1VyHTOl+pzOeZQdpH53QQSdgZcsnhGo9tPyR2iYSTKGUORIdO2RQAdF4O05mqQ03ryLg+OZJfyyIxNLk5/uaYf5WhPzeuLNXHzmf2PxTMPLkymdaWQAxFOd0PlZgLM1XFnSb8egYup3aRZe/SSJ8Ze97ne6nSysh66q545xS+UDU1leDhwC8zO3cwJP48wgEjT2e5eJyuQEkIWj7iAxU2OhxSFNVGfmqj2NLAPWM8MR5ewS5S4AjypMeTNHsWZNlgFEWG8xkOFBemxtNZI=